language: python
python:
  - "pypy"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - python setup.py -q install
script:
  - python -m unittest tests
  # Docs are in python 3 format
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then python -m doctest README.rst; fi
